name: ExampleApp
options:
  bundleIdPrefix: com.arclabsstudio
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"

packages:
  ARCNetworking:
    path: ../..

targets:
  ExampleApp:
    type: application
    platform: iOS
    sources:
      - ExampleApp
    dependencies:
      - package: ARCNetworking
    settings:
      base:
        INFOPLIST_GENERATION_MODE: GeneratedFile
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: "YES"
        PRODUCT_BUNDLE_IDENTIFIER: com.arclabsstudio.arcnetworking.example
        PRODUCT_NAME: "$(TARGET_NAME)"
        SWIFT_EMIT_LOC_STRINGS: "YES"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        DEVELOPMENT_TEAM: ""
